### ISSUE TITLE
希望能美化一下样式

### ISSUE THREAD

**Issue by mozhux** [OpaqueGlass/syplugin-my-plugin-collection#1]
目前的父子文档有两条横线比较碍眼，希望能类似HBX主题那样美化一下样式，并且是和文档标题对齐，更好的融入页面中。
![image](https://user-images.githubusercontent.com/46953371/232183204-63f92902-fda6-4e79-89aa-0802c097cec1.png)

**Comment by OpaqueGlass** [comment]
还有其他样式建议吗？或者哪些样式可能会需要自定义的？有空我全改掉
