### ISSUE TITLE
建议默认不展示兄文档，否则同级别太多太污染

### ISSUE THREAD

**Issue by mozhux** [OpaqueGlass/syplugin-my-plugin-collection#2]
如题，HBX主题也是担心兄文档太多展示污染所以没有，希望插件也能默认不展示
![image](https://user-images.githubusercontent.com/46953371/232183773-f67c0dc2-b70d-425d-a081-0b08f86ebd89.png)

**Comment by OpaqueGlass** [comment]
好的

**Comment by OpaqueGlass** [comment]
已修改，图标、兄弟文档显示与否可通过设置页面更改。
![image](https://user-images.githubusercontent.com/52985952/232956189-b3441a4b-1009-4d84-883a-ae0de1b0253c.png)
