### ISSUE TITLE
hierarchyNavigate 与文档的转移引用冲突，导致选项消失

### ISSUE THREAD

**Issue by zxhd863943427** [OpaqueGlass/syplugin-my-plugin-collection#4]
如图
![图片](https://user-images.githubusercontent.com/74853597/233973928-f68f7938-655f-43af-b818-5631eead28a6.png)

版本为GitHub上拷贝的最新版。

**Comment by OpaqueGlass** [comment]
收到，感谢反馈；
问题似乎出现在所有将新元素插入`.protyle-title`最后的主题&插件中（比如在标题下显示创建时间），插入新元素导致`.protyle-title`元素的最后一个子元素不为`.protyle-attr`。
新代码应该是修复了，麻烦测试一下，谢谢；

**Comment by zxhd863943427** [comment]
抱歉，这几天没怎么看邮箱，你刚刚关闭了issue才发现，经过测试，已经修复了，感谢你为社区贡献了这样一个优秀的插件。
